In [1]:
[1, 2, 3]

[1, 2, 3]

In [2]:
["abc", None, 42]

['abc', None, 42]

In [3]:
{"a": 1, "b": 2}

{'a': 1, 'b': 2}

In [4]:
(2, 3, 4)

(2, 3, 4)

In [5]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
[n**2 for n in range(5)]

[0, 1, 4, 9, 16]

In [8]:
l = []
for n in range(5):
    l.append(n**2)
l

[0, 1, 4, 9, 16]

In [9]:
{n**2 for n in range(5)}

{0, 1, 4, 9, 16}

In [10]:
{n: n**2 for n in range(5)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [11]:
[i*j for i in range(5) for j in range(2)]

[0, 0, 0, 1, 0, 2, 0, 3, 0, 4]

In [13]:
[[i*j for i in range(5)] for j in range(2)]

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4]]

In [14]:
np.concatenate([np.arange(10), 2*np.arange(10)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18])

In [15]:
l = [1, 2, 3]
l[1] = 42
l

[1, 42, 3]

In [16]:
t = (1, 2, 3)
t[1] = 41

TypeError: 'tuple' object does not support item assignment

In [17]:
l = [1, 2]
d = {l : "a"}
l[0] = 10
print d[[1, 2]]

TypeError: unhashable type: 'list'

In [19]:
from copy import copy, deepcopy
l = [1, 2]
d1 = l[:]
d2 = copy(l)
d3 = deepcopy(l)


In [20]:
d1, d2, d3

([1, 2], [1, 2], [1, 2])

In [21]:
l = [[1, 2], [3, 4]]
c = copy(l)
d = deepcopy(l)
l[0][0] = 10
print c
print d

[[10, 2], [3, 4]]
[[1, 2], [3, 4]]


In [22]:
c[0][0] = 100
print l

[[100, 2], [3, 4]]


In [23]:
c[0] is l[0]

True

In [24]:
c[1] is l[1]

True

In [25]:
d[1] is l[1]

False

In [26]:
d[1] == l[1]

True

In [27]:
id(l)

4377858272

In [28]:
id(l[0])

4377942640

In [29]:
id(c[0]) == id(l[0])
c[0] is l[0]

True

In [30]:
c is l

False

In [31]:
a = np.arange(10)

In [32]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a.base is None

True

In [35]:
b = a[::2]

In [36]:
b.base is None

False

In [37]:
b.base is a

True

In [38]:
a.base is None

True

In [39]:
b[0] = 42
a

array([42,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [42]:
a[2] = 100

In [43]:
b

array([ 42, 100,   4,   6,   8])

In [44]:
a = np.arange(10)
b = copy(a)[::2]

In [45]:
a, b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 2, 4, 6, 8]))

In [47]:
a[0] = 100

In [48]:
b

array([0, 2, 4, 6, 8])

In [49]:
type(2)

int

In [50]:
type('anc')

str

In [51]:
type(a)

numpy.ndarray

In [52]:
a + b

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [53]:
a + a

array([200,   2,   4,   6,   8,  10,  12,  14,  16,  18])

In [54]:
for element_of_a in a:
    element_of_a + element_of_a

# Exercises

Positive elements

In [55]:
x = np.arange(10)-5
print x

[-5 -4 -3 -2 -1  0  1  2  3  4]


In [56]:
def positive_elements(x):
    return np.repeat(x, x > 0)

print positive_elements(x)

[1 2 3 4]


Difference arrays

In [65]:
x = np.array([1., 2., -3., 0.])

In [66]:
def differences(x):
    return x[1:]-x[:-1]

print differences(x)

[ 1. -5.  3.]


Multiplication table

In [69]:
a = np.arange(3)
b = np.array([-1., 1., 2.])

In [73]:
def multiplication_table(a, b):
    return a[:, np.newaxis]*b[np.newaxis, :]

print multiplication_table(a, b)

[[-0.  0.  0.]
 [-1.  1.  2.]
 [-2.  2.  4.]]


In [57]:
x

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [58]:
x > 0

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [59]:
True + True

2

In [60]:
x[x>0]

array([1, 2, 3, 4])

In [63]:
x[np.where(x>0)]

array([1, 2, 3, 4])

In [64]:
np.where(x)

(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)

In [68]:
np.diff?

In [70]:
a.shape, b.shape

((3,), (3,))

In [72]:
a[:, np.newaxis]*b[np.newaxis, :]

array([[-0.,  0.,  0.],
       [-1.,  1.,  2.],
       [-2.,  2.,  4.]])